# -*- coding: utf-8 -*-
"""task7_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kfMc7iRn5-M4Hrk-1iGdRgF5OkeAPBk
"""

import random
from typing import List, Any, Union

def check_input(arr: List[Any]) -> bool:

    if not isinstance(arr, list) or len(arr) != 2:
        return False

    a, b = arr

    if not isinstance(a, int) or not isinstance(b, int):
        return False

    if a <= 0 or b <= 0:
        return False

    if a >= b:
        return False

    return True


def get_ladder(valid_array: List[int]) -> List[str]:

    A, B = valid_array

    N = random.randint(A, B)

    first_ladder = []
    for i in range(B, N - 1, -1):
        first_ladder.append('*' * i)

    second_ladder = []
    for i in range(A, N + 1):
        second_ladder.append('*' * i)

    result = first_ladder + second_ladder
    return result


def main(input_list: List[List[Any]]) -> None:

    valid_array = None
    for sublist in input_list:
        if check_input(sublist):
            valid_array = sublist
            break

    if valid_array is None:
        print("Валидный массив не найден!")
        return

    ladder_data = get_ladder(valid_array)

    for line in ladder_data:
        print(line)